// <auto-generated />
using System;
using AscendedGuild.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AscendedGuild.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200119221108_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AscendedGuild.Models.PlayerClass", b =>
                {
                    b.Property<int>("PlayerClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("PlayerClassId");

                    b.ToTable("PlayerClasses");

                    b.HasData(
                        new
                        {
                            PlayerClassId = 1,
                            ImageUrl = "/images/dk.png",
                            Name = "Death Knight"
                        },
                        new
                        {
                            PlayerClassId = 2,
                            ImageUrl = "/images/mage.png",
                            Name = "Mage"
                        },
                        new
                        {
                            PlayerClassId = 3,
                            ImageUrl = "/images/rogue.png",
                            Name = "Rogue"
                        },
                        new
                        {
                            PlayerClassId = 4,
                            ImageUrl = "/images/dh.png",
                            Name = "Demon Hunter"
                        },
                        new
                        {
                            PlayerClassId = 5,
                            ImageUrl = "/images/monk.png",
                            Name = "Monk"
                        },
                        new
                        {
                            PlayerClassId = 6,
                            ImageUrl = "/images/shaman.png",
                            Name = "Shaman"
                        },
                        new
                        {
                            PlayerClassId = 7,
                            ImageUrl = "/images/druid.png",
                            Name = "Druid"
                        },
                        new
                        {
                            PlayerClassId = 8,
                            ImageUrl = "/images/paladin.png",
                            Name = "Paladin"
                        },
                        new
                        {
                            PlayerClassId = 9,
                            ImageUrl = "/images/warlock.png",
                            Name = "Warlock"
                        },
                        new
                        {
                            PlayerClassId = 10,
                            ImageUrl = "/images/hunter.png",
                            Name = "Hunter"
                        },
                        new
                        {
                            PlayerClassId = 11,
                            ImageUrl = "/images/priest.png",
                            Name = "Priest"
                        },
                        new
                        {
                            PlayerClassId = 12,
                            ImageUrl = "/images/warrior.png",
                            Name = "Warrior"
                        });
                });

            modelBuilder.Entity("AscendedGuild.Models.PlayerClass", b =>
                {
                    b.OwnsMany("AscendedGuild.Models.Spec", "Specs", b1 =>
                        {
                            b1.Property<int>("PlayerClassId")
                                .HasColumnType("int");

                            b1.Property<Guid>("SpecId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("char(36)");

                            b1.Property<int>("Demand")
                                .HasColumnType("int");

                            b1.Property<string>("ImageUrl")
                                .HasColumnType("longtext CHARACTER SET utf8mb4");

                            b1.Property<string>("Name")
                                .HasColumnType("longtext CHARACTER SET utf8mb4");

                            b1.HasKey("PlayerClassId", "SpecId");

                            b1.ToTable("Spec");

                            b1.WithOwner()
                                .HasForeignKey("PlayerClassId");

                            b1.HasData(
                                new
                                {
                                    PlayerClassId = 1,
                                    SpecId = new Guid("c6560cc2-49f0-44b2-b5f0-236a430f1fde"),
                                    Demand = 0,
                                    ImageUrl = "/images/dk-blood.jpg",
                                    Name = "Blood"
                                },
                                new
                                {
                                    PlayerClassId = 1,
                                    SpecId = new Guid("bf5616bd-7f7f-4e46-8951-b863d643d6fa"),
                                    Demand = 0,
                                    ImageUrl = "/images/dk-frost.jpg",
                                    Name = "Frost"
                                },
                                new
                                {
                                    PlayerClassId = 1,
                                    SpecId = new Guid("5fab59d5-7ff7-402e-b7d1-87742a0d53d5"),
                                    Demand = 0,
                                    ImageUrl = "/images/dk-unholy.jpg",
                                    Name = "Unholy"
                                },
                                new
                                {
                                    PlayerClassId = 2,
                                    SpecId = new Guid("0e15b7c2-49fb-4fca-bc5d-1a1b27b8f5b2"),
                                    Demand = 0,
                                    ImageUrl = "/images/mage-arcane.jpg",
                                    Name = "Arcane"
                                },
                                new
                                {
                                    PlayerClassId = 2,
                                    SpecId = new Guid("ccf2c6e4-d68a-4759-97b7-14a4f26c4c9f"),
                                    Demand = 0,
                                    ImageUrl = "/images/mage-fire.jpg",
                                    Name = "Fire"
                                },
                                new
                                {
                                    PlayerClassId = 2,
                                    SpecId = new Guid("ad2c86ef-66f8-4e2c-9f61-26f100f36610"),
                                    Demand = 0,
                                    ImageUrl = "/images/mage-frost.jpg",
                                    Name = "Frost"
                                },
                                new
                                {
                                    PlayerClassId = 3,
                                    SpecId = new Guid("4554cd1d-26a9-4b75-aef0-0500fa88ad30"),
                                    Demand = 0,
                                    ImageUrl = "/images/rogue-assassination.jpg",
                                    Name = "Assassination"
                                },
                                new
                                {
                                    PlayerClassId = 3,
                                    SpecId = new Guid("9a79041c-95a6-4ce9-a485-809aa2294cc5"),
                                    Demand = 0,
                                    ImageUrl = "/images/rogue-outlaw.jpg",
                                    Name = "Outlaw"
                                },
                                new
                                {
                                    PlayerClassId = 3,
                                    SpecId = new Guid("dbccb283-3eb1-4620-a756-8ffc2a790298"),
                                    Demand = 0,
                                    ImageUrl = "/images/rogue-subtlety.jpg",
                                    Name = "Subtlety"
                                },
                                new
                                {
                                    PlayerClassId = 4,
                                    SpecId = new Guid("787a89c3-b350-49a9-80d6-be242b30b9a6"),
                                    Demand = 0,
                                    ImageUrl = "/images/dh-havoc.jpg",
                                    Name = "Havoc"
                                },
                                new
                                {
                                    PlayerClassId = 4,
                                    SpecId = new Guid("73ea710a-a3a0-4554-aef2-8ac4746a4391"),
                                    Demand = 0,
                                    ImageUrl = "/images/dh-vengeance.jpg",
                                    Name = "Vengeance"
                                },
                                new
                                {
                                    PlayerClassId = 5,
                                    SpecId = new Guid("18dad26d-20d5-4e0a-9835-ff95b38677b4"),
                                    Demand = 0,
                                    ImageUrl = "/images/monk-brewmaster.jpg",
                                    Name = "Brewmaster"
                                },
                                new
                                {
                                    PlayerClassId = 5,
                                    SpecId = new Guid("922d66ef-f443-4276-ae21-d9221b7cc91e"),
                                    Demand = 0,
                                    ImageUrl = "/images/monk-mistweaver.jpg",
                                    Name = "Mistweaver"
                                },
                                new
                                {
                                    PlayerClassId = 5,
                                    SpecId = new Guid("4d790602-7124-4e8b-af29-a49bc9809379"),
                                    Demand = 0,
                                    ImageUrl = "/images/monk-windwalker.jpg",
                                    Name = "Windwalker"
                                },
                                new
                                {
                                    PlayerClassId = 6,
                                    SpecId = new Guid("fe8499c3-42e4-4061-aa04-392c4f167f3c"),
                                    Demand = 0,
                                    ImageUrl = "/images/shaman-elemental.jpg",
                                    Name = "Elemental"
                                },
                                new
                                {
                                    PlayerClassId = 6,
                                    SpecId = new Guid("2204525b-6f49-44a1-8602-2c801b2d9e74"),
                                    Demand = 0,
                                    ImageUrl = "/images/shaman-enhancement.jpg",
                                    Name = "Enhancement"
                                },
                                new
                                {
                                    PlayerClassId = 6,
                                    SpecId = new Guid("09983a63-4030-4093-9d53-8548ef1d12ca"),
                                    Demand = 0,
                                    ImageUrl = "/images/shaman-restoration.jpg",
                                    Name = "Restoration"
                                },
                                new
                                {
                                    PlayerClassId = 7,
                                    SpecId = new Guid("b7ff1a1e-b9f2-4557-92e6-2e9fe22510ae"),
                                    Demand = 0,
                                    ImageUrl = "/images/druid-balance.jpg",
                                    Name = "Balance"
                                },
                                new
                                {
                                    PlayerClassId = 7,
                                    SpecId = new Guid("5eab143c-be2e-459b-983e-8a392176512b"),
                                    Demand = 0,
                                    ImageUrl = "/images/druid-feral.jpg",
                                    Name = "Feral"
                                },
                                new
                                {
                                    PlayerClassId = 7,
                                    SpecId = new Guid("ff99ccf2-58a4-410c-a8ba-e231232d8d7f"),
                                    Demand = 0,
                                    ImageUrl = "/images/druid-guardian.jpg",
                                    Name = "Guardian"
                                },
                                new
                                {
                                    PlayerClassId = 7,
                                    SpecId = new Guid("c82a7c08-4880-495e-a33e-46e3010e302b"),
                                    Demand = 0,
                                    ImageUrl = "/images/druid-restoration.jpg",
                                    Name = "Restoration"
                                },
                                new
                                {
                                    PlayerClassId = 8,
                                    SpecId = new Guid("85c07efd-e37c-4f6b-8c4d-1d242411d7af"),
                                    Demand = 0,
                                    ImageUrl = "/images/paladin-holy.jpg",
                                    Name = "Holy"
                                },
                                new
                                {
                                    PlayerClassId = 8,
                                    SpecId = new Guid("70a7f1e5-efcb-4994-8b3e-b8e23485a804"),
                                    Demand = 0,
                                    ImageUrl = "/images/paladin-protection.jpg",
                                    Name = "Protection"
                                },
                                new
                                {
                                    PlayerClassId = 8,
                                    SpecId = new Guid("f3696cb1-ee0b-4211-ad16-b5eef5d36fbb"),
                                    Demand = 0,
                                    ImageUrl = "/images/paladin-retribution.jpg",
                                    Name = "Retribution"
                                },
                                new
                                {
                                    PlayerClassId = 9,
                                    SpecId = new Guid("96d350fb-feaf-4d26-9f0f-c1843104669c"),
                                    Demand = 0,
                                    ImageUrl = "/images/warlock-affliction.jpg",
                                    Name = "Affliction"
                                },
                                new
                                {
                                    PlayerClassId = 9,
                                    SpecId = new Guid("9bb9a47c-7452-4d25-a203-44536d6c5493"),
                                    Demand = 0,
                                    ImageUrl = "/images/warlock-demonology.jpg",
                                    Name = "Demonology"
                                },
                                new
                                {
                                    PlayerClassId = 9,
                                    SpecId = new Guid("d0a85c59-2a51-4bb8-86dc-6c8a61b917ca"),
                                    Demand = 0,
                                    ImageUrl = "/images/warlock-destruction.jpg",
                                    Name = "Destruction"
                                },
                                new
                                {
                                    PlayerClassId = 10,
                                    SpecId = new Guid("8569a32e-805b-4e5b-ae97-e6ac4a0bbb5a"),
                                    Demand = 0,
                                    ImageUrl = "/images/hunter-bm.jpg",
                                    Name = "Beast Mastery"
                                },
                                new
                                {
                                    PlayerClassId = 10,
                                    SpecId = new Guid("5b5c6666-25bb-4589-9848-3330def9c9c8"),
                                    Demand = 0,
                                    ImageUrl = "/images/hunter-marksmanship.jpg",
                                    Name = "Marksmanship"
                                },
                                new
                                {
                                    PlayerClassId = 10,
                                    SpecId = new Guid("fed28f86-3580-4262-9b2d-1f6f55529e66"),
                                    Demand = 0,
                                    ImageUrl = "/images/hunter-survival.jpg",
                                    Name = "Survival"
                                },
                                new
                                {
                                    PlayerClassId = 11,
                                    SpecId = new Guid("21fe58a9-e4d3-4f25-b225-d9cf30ff0a0e"),
                                    Demand = 0,
                                    ImageUrl = "/images/priest-discipline.jpg",
                                    Name = "Discipline"
                                },
                                new
                                {
                                    PlayerClassId = 11,
                                    SpecId = new Guid("ac57893a-2446-45cf-8d1b-15442c9a8065"),
                                    Demand = 0,
                                    ImageUrl = "/images/priest-holy.jpg",
                                    Name = "Holy"
                                },
                                new
                                {
                                    PlayerClassId = 11,
                                    SpecId = new Guid("f0e1f6f7-931b-4b1f-973d-9bed1bf8e4ba"),
                                    Demand = 0,
                                    ImageUrl = "/images/priest-shadow.jpg",
                                    Name = "Shadow"
                                },
                                new
                                {
                                    PlayerClassId = 12,
                                    SpecId = new Guid("7e5baee7-f812-4f1e-aea3-fdc181faeb7e"),
                                    Demand = 0,
                                    ImageUrl = "/images/warrior-arms.jpg",
                                    Name = "Arms"
                                },
                                new
                                {
                                    PlayerClassId = 12,
                                    SpecId = new Guid("2cf2c599-d8b3-4ff2-abec-afa7da5508a6"),
                                    Demand = 0,
                                    ImageUrl = "/images/warrior-fury.jpg",
                                    Name = "Fury"
                                },
                                new
                                {
                                    PlayerClassId = 12,
                                    SpecId = new Guid("cd1369d6-dd98-44ae-b390-a36dee7e2aa2"),
                                    Demand = 0,
                                    ImageUrl = "/images/warrior-protection.jpg",
                                    Name = "Protection"
                                });
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
