// <auto-generated />
using System;
using AscendedGuild.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AscendedGuild.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200119230927_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AscendedGuild.Models.PlayerClass", b =>
                {
                    b.Property<int>("PlayerClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("PlayerClassId");

                    b.ToTable("PlayerClasses");

                    b.HasData(
                        new
                        {
                            PlayerClassId = 1,
                            ImageUrl = "/images/class-icons/dk.png",
                            Name = "Death Knight"
                        },
                        new
                        {
                            PlayerClassId = 2,
                            ImageUrl = "/images/class-icons/mage.png",
                            Name = "Mage"
                        },
                        new
                        {
                            PlayerClassId = 3,
                            ImageUrl = "/images/class-icons/rogue.png",
                            Name = "Rogue"
                        },
                        new
                        {
                            PlayerClassId = 4,
                            ImageUrl = "/images/class-icons/dh.png",
                            Name = "Demon Hunter"
                        },
                        new
                        {
                            PlayerClassId = 5,
                            ImageUrl = "/images/class-icons/monk.png",
                            Name = "Monk"
                        },
                        new
                        {
                            PlayerClassId = 6,
                            ImageUrl = "/images/class-icons/shaman.png",
                            Name = "Shaman"
                        },
                        new
                        {
                            PlayerClassId = 7,
                            ImageUrl = "/images/class-icons/druid.png",
                            Name = "Druid"
                        },
                        new
                        {
                            PlayerClassId = 8,
                            ImageUrl = "/images/class-icons/paladin.png",
                            Name = "Paladin"
                        },
                        new
                        {
                            PlayerClassId = 9,
                            ImageUrl = "/images/class-icons/warlock.png",
                            Name = "Warlock"
                        },
                        new
                        {
                            PlayerClassId = 10,
                            ImageUrl = "/images/class-icons/hunter.png",
                            Name = "Hunter"
                        },
                        new
                        {
                            PlayerClassId = 11,
                            ImageUrl = "/images/class-icons/priest.png",
                            Name = "Priest"
                        },
                        new
                        {
                            PlayerClassId = 12,
                            ImageUrl = "/images/class-icons/warrior.png",
                            Name = "Warrior"
                        });
                });

            modelBuilder.Entity("AscendedGuild.Models.PlayerClass", b =>
                {
                    b.OwnsMany("AscendedGuild.Models.Spec", "Specs", b1 =>
                        {
                            b1.Property<int>("PlayerClassId")
                                .HasColumnType("int");

                            b1.Property<Guid>("SpecId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("char(36)");

                            b1.Property<int>("Demand")
                                .HasColumnType("int");

                            b1.Property<string>("ImageUrl")
                                .HasColumnType("longtext CHARACTER SET utf8mb4");

                            b1.Property<string>("Name")
                                .HasColumnType("longtext CHARACTER SET utf8mb4");

                            b1.HasKey("PlayerClassId", "SpecId");

                            b1.ToTable("Spec");

                            b1.WithOwner()
                                .HasForeignKey("PlayerClassId");

                            b1.HasData(
                                new
                                {
                                    PlayerClassId = 1,
                                    SpecId = new Guid("7cfe1662-7a15-4703-af9b-bdc44865a83c"),
                                    Demand = 0,
                                    ImageUrl = "/images/class-icons/dk-blood.jpg",
                                    Name = "Blood"
                                },
                                new
                                {
                                    PlayerClassId = 1,
                                    SpecId = new Guid("5deb45dc-af3b-4335-b87f-b392c0cfca2f"),
                                    Demand = 0,
                                    ImageUrl = "/images/class-icons/dk-frost.jpg",
                                    Name = "Frost"
                                },
                                new
                                {
                                    PlayerClassId = 1,
                                    SpecId = new Guid("364555df-efcb-4815-943b-f27108c1c526"),
                                    Demand = 0,
                                    ImageUrl = "/images/class-icons/dk-unholy.jpg",
                                    Name = "Unholy"
                                },
                                new
                                {
                                    PlayerClassId = 2,
                                    SpecId = new Guid("bc664d09-93e4-4bf4-a844-d7e67f897041"),
                                    Demand = 0,
                                    ImageUrl = "/images/class-icons/mage-arcane.jpg",
                                    Name = "Arcane"
                                },
                                new
                                {
                                    PlayerClassId = 2,
                                    SpecId = new Guid("c9b0d180-273f-4f0d-b5d5-d2d3c578e1ee"),
                                    Demand = 0,
                                    ImageUrl = "/images/class-icons/mage-fire.jpg",
                                    Name = "Fire"
                                },
                                new
                                {
                                    PlayerClassId = 2,
                                    SpecId = new Guid("d0e3c779-bb61-4109-b10d-de31b3e3bb62"),
                                    Demand = 0,
                                    ImageUrl = "/images/class-icons/mage-frost.jpg",
                                    Name = "Frost"
                                },
                                new
                                {
                                    PlayerClassId = 3,
                                    SpecId = new Guid("7399c8e7-9a4b-42df-b137-30d45ae10a6e"),
                                    Demand = 0,
                                    ImageUrl = "/images/class-icons/rogue-assassination.jpg",
                                    Name = "Assassination"
                                },
                                new
                                {
                                    PlayerClassId = 3,
                                    SpecId = new Guid("f0e9016f-f348-41d9-a13a-920caed041e3"),
                                    Demand = 0,
                                    ImageUrl = "/images/class-icons/rogue-outlaw.jpg",
                                    Name = "Outlaw"
                                },
                                new
                                {
                                    PlayerClassId = 3,
                                    SpecId = new Guid("374f5aca-1323-4840-b26c-6e317ff1f353"),
                                    Demand = 0,
                                    ImageUrl = "/images/class-icons/rogue-subtlety.jpg",
                                    Name = "Subtlety"
                                },
                                new
                                {
                                    PlayerClassId = 4,
                                    SpecId = new Guid("e2ccae81-6a80-40fe-b25d-54dfbf8592c5"),
                                    Demand = 0,
                                    ImageUrl = "/images/class-icons/dh-havoc.jpg",
                                    Name = "Havoc"
                                },
                                new
                                {
                                    PlayerClassId = 4,
                                    SpecId = new Guid("3318bc67-eeea-4252-a3a3-62d64510d33e"),
                                    Demand = 0,
                                    ImageUrl = "/images/class-icons/dh-vengeance.jpg",
                                    Name = "Vengeance"
                                },
                                new
                                {
                                    PlayerClassId = 5,
                                    SpecId = new Guid("f5e814f8-3233-4c63-a94b-15de864d19e4"),
                                    Demand = 0,
                                    ImageUrl = "/images/class-icons/monk-brewmaster.jpg",
                                    Name = "Brewmaster"
                                },
                                new
                                {
                                    PlayerClassId = 5,
                                    SpecId = new Guid("27487a76-70e9-4ca2-af17-4cdde9997165"),
                                    Demand = 0,
                                    ImageUrl = "/images/class-icons/monk-mistweaver.jpg",
                                    Name = "Mistweaver"
                                },
                                new
                                {
                                    PlayerClassId = 5,
                                    SpecId = new Guid("7bcfa67b-d2f8-4b5b-a229-931b5f0a24db"),
                                    Demand = 0,
                                    ImageUrl = "/images/class-icons/monk-windwalker.jpg",
                                    Name = "Windwalker"
                                },
                                new
                                {
                                    PlayerClassId = 6,
                                    SpecId = new Guid("2c6f8ea4-e56e-46fe-bf65-85f5745c7c75"),
                                    Demand = 0,
                                    ImageUrl = "/images/class-icons/shaman-elemental.jpg",
                                    Name = "Elemental"
                                },
                                new
                                {
                                    PlayerClassId = 6,
                                    SpecId = new Guid("9d210045-cd1e-461f-a9b2-382f3bcb9701"),
                                    Demand = 0,
                                    ImageUrl = "/images/class-icons/shaman-enhancement.jpg",
                                    Name = "Enhancement"
                                },
                                new
                                {
                                    PlayerClassId = 6,
                                    SpecId = new Guid("6fcaaf4c-7379-4c68-9f13-3a018154d459"),
                                    Demand = 0,
                                    ImageUrl = "/images/class-icons/shaman-restoration.jpg",
                                    Name = "Restoration"
                                },
                                new
                                {
                                    PlayerClassId = 7,
                                    SpecId = new Guid("1b63dce3-d7c0-48de-a127-b660a6f4c80b"),
                                    Demand = 0,
                                    ImageUrl = "/images/class-icons/druid-balance.jpg",
                                    Name = "Balance"
                                },
                                new
                                {
                                    PlayerClassId = 7,
                                    SpecId = new Guid("c42ae962-f8cb-41bd-a6a5-53e8fa1d215b"),
                                    Demand = 0,
                                    ImageUrl = "/images/class-icons/druid-feral.jpg",
                                    Name = "Feral"
                                },
                                new
                                {
                                    PlayerClassId = 7,
                                    SpecId = new Guid("732df4fc-3815-4ffd-9317-ca507060a0d3"),
                                    Demand = 0,
                                    ImageUrl = "/images/class-icons/druid-guardian.jpg",
                                    Name = "Guardian"
                                },
                                new
                                {
                                    PlayerClassId = 7,
                                    SpecId = new Guid("ec650abb-e334-4b6f-aab2-c239670c682c"),
                                    Demand = 0,
                                    ImageUrl = "/images/class-icons/druid-restoration.jpg",
                                    Name = "Restoration"
                                },
                                new
                                {
                                    PlayerClassId = 8,
                                    SpecId = new Guid("bbc9b896-0203-4b72-b443-21db88e624a3"),
                                    Demand = 0,
                                    ImageUrl = "/images/class-icons/paladin-holy.jpg",
                                    Name = "Holy"
                                },
                                new
                                {
                                    PlayerClassId = 8,
                                    SpecId = new Guid("acdc1873-6103-4e43-9855-01f8246e69d5"),
                                    Demand = 0,
                                    ImageUrl = "/images/class-icons/paladin-protection.jpg",
                                    Name = "Protection"
                                },
                                new
                                {
                                    PlayerClassId = 8,
                                    SpecId = new Guid("f192b2d6-8f5f-429b-b0fe-c0afd679fda8"),
                                    Demand = 0,
                                    ImageUrl = "/images/class-icons/paladin-retribution.jpg",
                                    Name = "Retribution"
                                },
                                new
                                {
                                    PlayerClassId = 9,
                                    SpecId = new Guid("9eeda09f-c86f-45ac-9ac3-90e64a3c91d3"),
                                    Demand = 0,
                                    ImageUrl = "/images/class-icons/warlock-affliction.jpg",
                                    Name = "Affliction"
                                },
                                new
                                {
                                    PlayerClassId = 9,
                                    SpecId = new Guid("a6c2df25-611c-44a5-99b7-968518219833"),
                                    Demand = 0,
                                    ImageUrl = "/images/class-icons/warlock-demonology.jpg",
                                    Name = "Demonology"
                                },
                                new
                                {
                                    PlayerClassId = 9,
                                    SpecId = new Guid("bf949bb1-0e98-4297-ab15-29648d59adbe"),
                                    Demand = 0,
                                    ImageUrl = "/images/class-icons/warlock-destruction.jpg",
                                    Name = "Destruction"
                                },
                                new
                                {
                                    PlayerClassId = 10,
                                    SpecId = new Guid("0c69f2f0-33a5-4181-b374-25b64c27be21"),
                                    Demand = 0,
                                    ImageUrl = "/images/class-icons/hunter-bm.jpg",
                                    Name = "Beast Mastery"
                                },
                                new
                                {
                                    PlayerClassId = 10,
                                    SpecId = new Guid("65ee523b-ef2e-48a4-94cf-f460b1b964be"),
                                    Demand = 0,
                                    ImageUrl = "/images/class-icons/hunter-marksmanship.jpg",
                                    Name = "Marksmanship"
                                },
                                new
                                {
                                    PlayerClassId = 10,
                                    SpecId = new Guid("d0c2aba8-defb-4a31-b28c-c986d05b2d63"),
                                    Demand = 0,
                                    ImageUrl = "/images/class-icons/hunter-survival.jpg",
                                    Name = "Survival"
                                },
                                new
                                {
                                    PlayerClassId = 11,
                                    SpecId = new Guid("ec609361-14c1-49b4-9629-606402262513"),
                                    Demand = 0,
                                    ImageUrl = "/images/class-icons/priest-discipline.jpg",
                                    Name = "Discipline"
                                },
                                new
                                {
                                    PlayerClassId = 11,
                                    SpecId = new Guid("0af543c9-0486-42a7-9613-d5d7096a8013"),
                                    Demand = 0,
                                    ImageUrl = "/images/class-icons/priest-holy.jpg",
                                    Name = "Holy"
                                },
                                new
                                {
                                    PlayerClassId = 11,
                                    SpecId = new Guid("534447f5-33cb-4602-9db2-dfcadef0c945"),
                                    Demand = 0,
                                    ImageUrl = "/images/class-icons/priest-shadow.jpg",
                                    Name = "Shadow"
                                },
                                new
                                {
                                    PlayerClassId = 12,
                                    SpecId = new Guid("0481451c-b098-4c84-a4a2-cd328a3e5bac"),
                                    Demand = 0,
                                    ImageUrl = "/images/class-icons/warrior-arms.jpg",
                                    Name = "Arms"
                                },
                                new
                                {
                                    PlayerClassId = 12,
                                    SpecId = new Guid("61c8467d-4752-4fef-bb03-b953b3f3d632"),
                                    Demand = 0,
                                    ImageUrl = "/images/class-icons/warrior-fury.jpg",
                                    Name = "Fury"
                                },
                                new
                                {
                                    PlayerClassId = 12,
                                    SpecId = new Guid("082651b9-6320-4229-8295-eea8ed65780e"),
                                    Demand = 0,
                                    ImageUrl = "/images/class-icons/warrior-protection.jpg",
                                    Name = "Protection"
                                });
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
